from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('',home,name='home'),
    path('signup/', signup_view, name='signup'),
    path('predict/', predict_view, name='predict'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('history/', user_history_view, name='user_history'),
    path('history_delete/<int:id>/', user_delete_prediction, name='user_delete_prediction'),
    path('profile/', profile_view, name='profile'),
    path('change_password/', change_password_view, name='change_password'),
    path('forgot_password/', forgot_password_view, name='forgot_password'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path('notifications/', notifications_view, name='notifications'),
    path('notifications/read/<int:notification_id>/', mark_notification_read, name='mark_notification_read'),
    path('notifications/delete/<int:notification_id>/', delete_notification, name='delete_notification'),
    path('admin_login/', admin_login_view, name='admin_login'),
    path('admin_dashboard/', admin_dashboard_view, name='admin_dashboard'),
    path('admin_predictions/', admin_predictions_view, name='admin_predictions'),
    path('admin_users/', admin_users_view, name='admin_users'),
    path('admin_feedback/', admin_feedback_view, name='admin_feedback'),
    path('delete_user/<int:user_id>/', delete_user_view, name='delete_user'),
    path('export_predictions_csv/', export_predictions_csv, name='export_predictions_csv'),
    path('export_predictions_pdf/', export_predictions_pdf, name='export_predictions_pdf'),
    path('export_user_predictions_csv/', export_user_predictions_csv, name='export_user_predictions_csv'),
    path('analytics/', analytics_view, name='analytics'),
    path('favorites/', favorites_view, name='favorites'),
    path('favorites/remove/<int:crop_id>/', remove_favorite_view, name='remove_favorite'),
    path('feedback/', feedback_view, name='feedback'),
    path('crop_calendar/', crop_calendar_view, name='crop_calendar'),
    path('compare_crops/', compare_crops_view, name='compare_crops'),
    path('chatbot/', chatbot_view, name='chatbot'),
    path('chatbot/clear/', clear_chat, name='clear_chat'),
    path('fertilizer/', fertilizer_recommendation_view, name='fertilizer'),
    path('disease_detection/', disease_detection_view, name='disease_detection'),
    path('map_location/', map_location_view, name='map_location'),
    path('farmer-connect/', farmer_connect_view, name='farmer_connect'),
    path('about/', about_view, name='about'),
    path('api/weather/', weather_json_view, name='weather_json'),
]